### ISSUE TITLE
Unexpected token <

### ISSUE THREAD

**Issue by mqklin** [gaearon/react-hot-boilerplate#55]
I've just made `npm install` and `npm start` and got `Unexpected token <`. I can't understand, why it's not working from scratch?

**Comment by aaronshaf** [comment]
Same here.

**Comment by aaronshaf** [comment]
You are probably missing the dot files.

**Comment by gaearon** [comment]
Yes, you probably missed `.babelrc` and friends when copying the folder because they are hidden on the desktop. Please try running `git clone` and then running `npm install` in that directory.

**Comment by mqklin** [comment]
@gaearon, so update npm module, it doesn't contain these files.

**Comment by gaearon** [comment]
I'm not sure why I published it to npm at all, I should probably unpublish.
npm is only useful for dependencies. There is no point installing something from npm and then changing it (npm doesn't support that), but boilerplate is meant for changing locally.

**Comment by mqklin** [comment]
@gaearon, so, you should either unpublish or update it, because it's non-working)

**Comment by gaearon** [comment]
It can't possibly work. I will unpublish it.

I'm not sure what you tried to do because people are not supposed to change code inside node_modules which is what you would do if you tried to use this boilerplate. I didn't completely understand how npm works when I published this.

**Comment by mqklin** [comment]
@gaearon, I still don't understand how they work. I download it from npm out of habit. Npm packages can't contain dot files?

**Comment by gaearon** [comment]
They can, but the NPM copy is terribly outdated so I don't even remember what's there.
For boilerplates you intend to run and modify, just use git clone.
